# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Xie He
description:      'Applied Math PhD student at UNC Chapel Hill'
url:              https://hexie1995.github.io/
baseurl:          ""

# Options: 7, 8, 9, a, b, c, d, e, f
theme_id: "d"

author:
  name:           'Xie He'
  url:            https://hexie1995.github.io

# Blog configuration
has_blog:         False
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"



# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
