# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
description:      'Hi, this is Xie. I am a first year Ph.D. student at UNC-Chapel Hill Mathematics department.'
url:              https://hexie1995.github.io/
baseurl:          ""

# Options: 7, 8, 9, a, b, c, d, e, f
theme_id: "7"

author:
  name:           'Xie He'
  url:            https://hexie1995.github.io

# Blog configuration
has_blog:         True
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"

# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
